// Generated by Haxe 3.3.0 (git build development @ e971ea1)
(function () { "use strict";
var Test = function() { };
Test.main = function() {
	console.log(1);
	console.log(2);
	console.log(3);
};
Test.main();
})();

//# sourceMappingURL=test.js.map